title: daniel.ga/llegos
description: >
  ğŸ”® code alchemist. 
  â­ digital storyteller. 
  ğŸ’š huge nerd.
url: "https://daniel.ga/"
baseurl: ""
twitter_username: takouhai
github_username:  takouhai

markdown: kramdown

kramdown: 
  parse_html_block: true

sass:
  sass_dir: _sass
  style: compressed